### PR TITLE
Support multiple selections

### PR DESCRIPTION
**Pull request by vovkkk**
Is there a way to expand / collapse all the directory.
I want to use FileBrowser to rename my files in different folders, but I have to expand all the directories manually.
It would be nice if there is a way to expand / collapse all the directory or list all the files matching a pattern, so I can rename them easily.

### CODE REVIEW

**Comment by vovkkk** [comment]
Intresting fact, Avast go crazy when I expand many folders at once — 100% CPU.

Could you guys let me know how it goes with other antiviruses or without one, Linux, OSX?

**Comment by vovkkk** [comment]
@aziz @bbtfr and anyone else interested, I think it is done, let’s test it few days in case some overlooked issues appear, if you guys won’t tell me about any problems until this weekend, I’ll rebase and commit into master.

**Comment by aziz** [comment]
Great work @vovkkk 

Here is what I've found so far:

- The ↑ key does not work when the first item in the list is selected. in other words can not go to `..` by pressing ↑ key

**Comment by aziz** [comment]
Found another one, empty folders are causing errors. Here is how to recreate it:
Select two folders, one that's empty and another that has content. open them once, it's ok. close them. open again. Error. 

```
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text-dev/Build 3062/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "/Users/allen.bargi/Library/Application Support/Sublime Text 3/Packages/FileBrowser/dired.py", line 393, in run
    return self.treeview(edit, path, filenames)
  File "/Users/allen.bargi/Library/Application Support/Sublime Text 3/Packages/FileBrowser/dired.py", line 486, in treeview
    self.view.replace(edit, region, '\n'.join(reversed(filelist)))
TypeError: sequence item 0: expected str instance, NoneType found
```

Dealing with empty folders in single selection is a bit unintuitive at the moment. Expanding as empty folder we show `<empty>` in red which is really nice but we forget to do a couple of things. 
1. put the folder in expanded mode (icon should be ▾) and when we fold and close we should remove
<empty> and put the folder icon back to normal mode.

**Comment by aziz** [comment]
Refreshing a folder with no expanded folders is ok but if we have an expanded folder the `..` is missing.

**Comment by aziz** [comment]
I'm getting this error, and I don't know exactly how I caused it! 
```
  File "/opt/homebrew-cask/Caskroom/sublime-text-dev/Build 3062/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
TypeError: run() got an unexpected keyword argument 'inline'
```

**Comment by aziz** [comment]
Can not remember the expanded folder coming out of the *Rename mode*.

**Comment by vovkkk** [comment]
Updated



> 1. put the folder in expanded mode (icon should be ▾) and when we fold and close we should remove
> and put the folder icon back to normal mode.

But empty folder cannot be expanded, thus icon shouldn’t be changed



> I'm getting this error, and I don't know exactly how I caused it!

Probably, plugin wasn’t reload properly, restart should fix it.

**Comment by aziz** [comment]
> But empty folder cannot be expanded, thus icon shouldn’t be changed

This is not the behavior of Finder in mac at least. opening an empty folder in Finder is just changing it's disclosure triangles (pointing down) and closing it set the disclosure triangles to the normal mode. 
I guess it should be the same in File Explorer.

> Probably, plugin wasn’t reload properly, restart should fix it.
Yes, restarting fixed it.

**Comment by vovkkk** [comment]
Okay, in this case I need one more day to make sure that change won’t break anything.

**Comment by aziz** [comment]
:+1:

**Comment by vovkkk** [comment]
Updated.

Also, I decide to recreate entire tree when user expand using multiple selections, although it is slower, this way expanding will be more reliable and code simplier.
As a side effect pressing <kbd>→</kbd> on file item will cause refresh, which is not a problem I think, is it?

**Comment by aziz** [comment]
:+1: I'm quite happy with frequent refreshes, at the moment they look pretty snappy and these frequent refreshes will help the content to look more up to date, e.g. when you change a file under version control or add a file using another method that this plugin does not know. 
Great job @vovkkk 
let's merge it to the master but wait for me to implement the shortcut changes and then we can release 0.6.0

**Comment by bbtfr** [comment]
@vovkkk sorry for reply late, and thanks for your patch :+1:

**Pull request closed without merging**
